repos:
  - repo: local
    hooks:
      - id: veritas-check
        name: veritas check (local)
        entry: python -m veritas.vertex.cli check
        language: system
        pass_filenames: false
        fail_fast: true
        always_run: true