name: Verify

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  veritas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc graphviz texlive-xetex texlive-fonts-recommended

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Install elan (Lean toolchain)
        run: |
          curl -sSfL https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Cache Lake packages
        uses: actions/cache@v4
        with:
          path: .lake/packages
          key: ${{ runner.os }}-lake-${{ hashFiles('lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lake-

      - name: Verify (veritas)
        run: veritas check --concurrency=1

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: publication
          path: |
            build/artifacts/article_blackhole_inevitable.pdf
            build/artifacts/article_blackhole_inevitable.docx

